from PyQtUIkit.themes.local import KitLocal

local = KitLocal('en', 'English', {
    'select_chat': "Select chat",
    'error': "Error",
    'connection_error': "The action failed. Check your internet connection.",
    'default_chat_name': "<New chat>",
    'delete': "Delete",
    'pin': "Pin",
    'unpin': "Unpin",
    'chat': "Chat",
    'gpt_print': "GPT prints...",
    'message_placeholder': "Message...",
    'send': "Send",
    'send_without_request': "Send without request",
    'translate_to': "Translate to ...",
    'translate_to_local': "Translate to English",
    'translate_to_english': "Translate into English",
    'reply': "Answer",
    'select_all': "Select all",
    'copy_as_text': "Copy as text",
    'copy_as_markdown': "Copy as Markdown",
    'show_original': "Show original",
    'translated_from': "Translated from",
    'search': "Search",
    'chat_name': "Chat name",
    'model': "Model",
    'used_messages': "Messages used",
    'max_messages': "Maximum messages",
    'temperature': "Temperature",
    'sync': "Synchronize",
    'created': "Created at",
    'settings': "Settings",
    'dark_theme': "Dark theme",
    'theme_color': "Theme color",
    'report_updates': "Report updates",
    'patch_note': "Patch note",
    'check_update': "Check update",
    'download_update': "Download update",
    'install_update': "Install update",
    'last_version_installed': "The latest version of the program is installed",
    'update': "Update",
    'check_update_connection_error': "Failed to check for update: no internet connection",
    'new_version_available': "New version of the program is available",
    'want_to_download_update': "Do you want to download the update now?",
    'sodo_required': "Superuser rights are required for installation",
    'ready_to_install': "Version {} is ready for installation",
    'install_now': "Install now?",
    'no': "No",
    'yes': "Yes",
    'version': "Version",
    'current_version': "Current",
    'last_version': "Previous",
    'next_version': "Not installed",
    'authorization': "Authorization",
    'password': "Password",
    'email': "Email",
    'sign_in': "Sign in",
    'reset_password': "Reset password",
    'sign_up': "Sign up",
    'oauth': "Login via:",
    'wrong_password': "wrong login or password",
    'wrong_email': "Incorrect email",
    'password_missing': "Please enter password",
    'unknown_error': "Unknown error",
    'auth_connection_error': "No internet connection",
    'password_again': "Password again",
    'create_account': "Create an account",
    'passwords_not_match': "Password mismatch",
    'account_exists': "Account already exists",
    'missing_email': "Please enter email",
    'too_short_password': "Too short password",
    'back': "Back",
    'send_again': "Send again",
    'email_send': "An email has been sent to your address {}. Follow the link in this email to verify your email address.",
    'sign_out': "Sign out",
    'copy_code': "Copy the code and follow the link",
    'sign_in_via': "Login via",

    'blue': "Blue",
    'green': "Green",
    'red': "Red",
    'pink': "Pink",
    'orange': "Orange",

    'lang_af': 'afrikaans',
    'lang_sq': 'albanian',
    'lang_am': 'amharic',
    'lang_ar': 'arabic',
    'lang_hy': 'armenian',
    'lang_az': 'azerbaijani',
    'lang_eu': 'basque',
    'lang_be': 'belarusian',
    'lang_bn': 'bengali',
    'lang_bs': 'bosnian',
    'lang_bg': 'bulgarian',
    'lang_ca': 'catalan',
    'lang_ceb': 'cebuano',
    'lang_ny': 'chichewa',
    'lang_zh-cn': 'chinese (simplified)',
    'lang_zh-tw': 'chinese (traditional)',
    'lang_co': 'corsican',
    'lang_hr': 'croatian',
    'lang_cs': 'czech',
    'lang_da': 'danish',
    'lang_nl': 'dutch',
    'lang_en': 'english',
    'lang_eo': 'esperanto',
    'lang_et': 'estonian',
    'lang_tl': 'filipino',
    'lang_fi': 'finnish',
    'lang_fr': 'french',
    'lang_fy': 'frisian',
    'lang_gl': 'galician',
    'lang_ka': 'georgian',
    'lang_de': 'german',
    'lang_el': 'greek',
    'lang_gu': 'gujarati',
    'lang_ht': 'haitian creole',
    'lang_ha': 'hausa',
    'lang_haw': 'hawaiian',
    'lang_iw': 'hebrew',
    'lang_he': 'hebrew',
    'lang_hi': 'hindi',
    'lang_hmn': 'hmong',
    'lang_hu': 'hungarian',
    'lang_is': 'icelandic',
    'lang_ig': 'igbo',
    'lang_id': 'indonesian',
    'lang_ga': 'irish',
    'lang_it': 'italian',
    'lang_ja': 'japanese',
    'lang_jw': 'javanese',
    'lang_kn': 'kannada',
    'lang_kk': 'kazakh',
    'lang_km': 'khmer',
    'lang_ko': 'korean',
    'lang_ku': 'kurdish (kurmanji)',
    'lang_ky': 'kyrgyz',
    'lang_lo': 'lao',
    'lang_la': 'latin',
    'lang_lv': 'latvian',
    'lang_lt': 'lithuanian',
    'lang_lb': 'luxembourgish',
    'lang_mk': 'macedonian',
    'lang_mg': 'malagasy',
    'lang_ms': 'malay',
    'lang_ml': 'malayalam',
    'lang_mt': 'maltese',
    'lang_mi': 'maori',
    'lang_mr': 'marathi',
    'lang_mn': 'mongolian',
    'lang_my': 'myanmar (burmese)',
    'lang_ne': 'nepali',
    'lang_no': 'norwegian',
    'lang_or': 'odia',
    'lang_ps': 'pashto',
    'lang_fa': 'persian',
    'lang_pl': 'polish',
    'lang_pt': 'portuguese',
    'lang_pa': 'punjabi',
    'lang_ro': 'romanian',
    'lang_ru': 'russian',
    'lang_sm': 'samoan',
    'lang_gd': 'scots gaelic',
    'lang_sr': 'serbian',
    'lang_st': 'sesotho',
    'lang_sn': 'shona',
    'lang_sd': 'sindhi',
    'lang_si': 'sinhala',
    'lang_sk': 'slovak',
    'lang_sl': 'slovenian',
    'lang_so': 'somali',
    'lang_es': 'spanish',
    'lang_su': 'sundanese',
    'lang_sw': 'swahili',
    'lang_sv': 'swedish',
    'lang_tg': 'tajik',
    'lang_ta': 'tamil',
    'lang_te': 'telugu',
    'lang_th': 'thai',
    'lang_tr': 'turkish',
    'lang_uk': 'ukrainian',
    'lang_ur': 'urdu',
    'lang_ug': 'uyghur',
    'lang_uz': 'uzbek',
    'lang_vi': 'vietnamese',
    'lang_cy': 'welsh',
    'lang_xh': 'xhosa',
    'lang_yi': 'yiddish',
    'lang_yo': 'yoruba',
    'lang_zu': 'zulu',

    'translated_from_af': 'Translated from afrikaans',
    'translated_from_sq': 'Translated from albanian',
    'translated_from_am': 'Translated from amharic',
    'translated_from_ar': 'Translated from arabic',
    'translated_from_hy': 'Translated from armenian',
    'translated_from_az': 'Translated from azerbaijani',
    'translated_from_eu': 'Translated from basque',
    'translated_from_be': 'Translated from belarusian',
    'translated_from_bn': 'Translated from bengali',
    'translated_from_bs': 'Translated from bosnian',
    'translated_from_bg': 'Translated from bulgarian',
    'translated_from_ca': 'Translated from catalan',
    'translated_from_ceb': 'Translated from cebuano',
    'translated_from_ny': 'Translated from chichewa',
    'translated_from_zh-cn': 'Translated from chinese (simplified)',
    'translated_from_zh-tw': 'Translated from chinese (traditional)',
    'translated_from_co': 'Translated from corsican',
    'translated_from_hr': 'Translated from croatian',
    'translated_from_cs': 'Translated from czech',
    'translated_from_da': 'Translated from danish',
    'translated_from_nl': 'Translated from dutch',
    'translated_from_en': 'Translated from english',
    'translated_from_eo': 'Translated from esperanto',
    'translated_from_et': 'Translated from estonian',
    'translated_from_tl': 'Translated from filipino',
    'translated_from_fi': 'Translated from finnish',
    'translated_from_fr': 'Translated from french',
    'translated_from_fy': 'Translated from frisian',
    'translated_from_gl': 'Translated from galician',
    'translated_from_ka': 'Translated from georgian',
    'translated_from_de': 'Translated from german',
    'translated_from_el': 'Translated from greek',
    'translated_from_gu': 'Translated from gujarati',
    'translated_from_ht': 'Translated from haitian creole',
    'translated_from_ha': 'Translated from hausa',
    'translated_from_haw': 'Translated from hawaiian',
    'translated_from_iw': 'Translated from hebrew',
    'translated_from_he': 'Translated from hebrew',
    'translated_from_hi': 'Translated from hindi',
    'translated_from_hmn': 'Translated from hmong',
    'translated_from_hu': 'Translated from hungarian',
    'translated_from_is': 'Translated from icelandic',
    'translated_from_ig': 'Translated from igbo',
    'translated_from_id': 'Translated from indonesian',
    'translated_from_ga': 'Translated from irish',
    'translated_from_it': 'Translated from italian',
    'translated_from_ja': 'Translated from japanese',
    'translated_from_jw': 'Translated from javanese',
    'translated_from_kn': 'Translated from kannada',
    'translated_from_kk': 'Translated from kazakh',
    'translated_from_km': 'Translated from khmer',
    'translated_from_ko': 'Translated from korean',
    'translated_from_ku': 'Translated from kurdish (kurmanji)',
    'translated_from_ky': 'Translated from kyrgyz',
    'translated_from_lo': 'Translated from lao',
    'translated_from_la': 'Translated from latin',
    'translated_from_lv': 'Translated from latvian',
    'translated_from_lt': 'Translated from lithuanian',
    'translated_from_lb': 'Translated from luxembourgish',
    'translated_from_mk': 'Translated from macedonian',
    'translated_from_mg': 'Translated from malagasy',
    'translated_from_ms': 'Translated from malay',
    'translated_from_ml': 'Translated from malayalam',
    'translated_from_mt': 'Translated from maltese',
    'translated_from_mi': 'Translated from maori',
    'translated_from_mr': 'Translated from marathi',
    'translated_from_mn': 'Translated from mongolian',
    'translated_from_my': 'Translated from myanmar (burmese)',
    'translated_from_ne': 'Translated from nepali',
    'translated_from_no': 'Translated from norwegian',
    'translated_from_or': 'Translated from odia',
    'translated_from_ps': 'Translated from pashto',
    'translated_from_fa': 'Translated from persian',
    'translated_from_pl': 'Translated from polish',
    'translated_from_pt': 'Translated from portuguese',
    'translated_from_pa': 'Translated from punjabi',
    'translated_from_ro': 'Translated from romanian',
    'translated_from_ru': 'Translated from russian',
    'translated_from_sm': 'Translated from samoan',
    'translated_from_gd': 'Translated from scots gaelic',
    'translated_from_sr': 'Translated from serbian',
    'translated_from_st': 'Translated from sesotho',
    'translated_from_sn': 'Translated from shona',
    'translated_from_sd': 'Translated from sindhi',
    'translated_from_si': 'Translated from sinhala',
    'translated_from_sk': 'Translated from slovak',
    'translated_from_sl': 'Translated from slovenian',
    'translated_from_so': 'Translated from somali',
    'translated_from_es': 'Translated from spanish',
    'translated_from_su': 'Translated from sundanese',
    'translated_from_sw': 'Translated from swahili',
    'translated_from_sv': 'Translated from swedish',
    'translated_from_tg': 'Translated from tajik',
    'translated_from_ta': 'Translated from tamil',
    'translated_from_te': 'Translated from telugu',
    'translated_from_th': 'Translated from thai',
    'translated_from_tr': 'Translated from turkish',
    'translated_from_uk': 'Translated from ukrainian',
    'translated_from_ur': 'Translated from urdu',
    'translated_from_ug': 'Translated from uyghur',
    'translated_from_uz': 'Translated from uzbek',
    'translated_from_vi': 'Translated from vietnamese',
    'translated_from_cy': 'Translated from welsh',
    'translated_from_xh': 'Translated from xhosa',
    'translated_from_yi': 'Translated from yiddish',
    'translated_from_yo': 'Translated from yoruba',
    'translated_from_zu': 'Translated from zulu',
})
