from PyQtUIkit.themes.local import KitLocal

local = KitLocal('ru', "Русский", {
    'select_chat': "Выберите чат",
    'error': "Ошибка",
    'connection_error': "Не удалось выполнить действие. Проверьте подключение к интернету.",
    'default_chat_name': "<Новый чат>",
    'delete': "Удалить",
    'pin': "Закрепить",
    'unpin': "Открепить",
    'chat': "Чат",
    'gpt_print': "GPT печатает...",
    'message_placeholder': "Сообщение...",
    'send': "Отправить",
    'send_without_request': "Отправить без запроса",
    'translate_to': "Перевести на ...",
    'translate_to_local': "Перевести на русский",
    'translate_to_english': "Перевести на английский",
    'reply': "Ответить",
    'select_all': "Выделить все",
    'copy_as_text': "Копировать как текст",
    'copy_as_markdown': "Копировать как Markdown",
    'show_original': "Показать оригинал",
    'translated_from': "Переведено с",
    'search': "Поиск",
    'chat_name': "Название чата",
    'model': "Модель",
    'used_messages': "Используемые сообщения",
    'max_messages': "Максимум сообщений",
    'temperature': "Temperature",
    'sync': "Синхронизировать",
    'created': "Создан",
    'settings': "Настройки",
    'dark_theme': "Темная тема",
    'theme_color': "Оформление",
    'report_updates': "Сообщать об обновлениях",
    'patch_note': "Описание обновления",
    'check_update': "Проверить обновление",
    'download_update': "Скачать обновление",
    'install_update': "Установить обновление",
    'last_version_installed': "Установлена последняя версия программы",
    'update': "Обновление",
    'check_update_connection_error': "Не удалось проверить наличие обновления: нет подключения к интернету",
    'new_version_available': "Доступна новая версия программы",
    'want_to_download_update': "Хотите загрузить обновление сейчас?",
    'sodo_required': "Для установки нужны права суперпользователя",
    'ready_to_install': "Версия {} готова к установке",
    'install_now': "Установить сейчас?",
    'no': "Нет",
    'yes': "Да",
    'version': "Версия",
    'current_version': "Текущая",
    'last_version': "Предыдущая",
    'next_version': "Не установлена",
    'authorization': "Авторизация",
    'password': "Пароль",
    'email': "Email",
    'sign_in': "Войти",
    'reset_password': "Сбросить пароль",
    'sign_up': "Регистрация",
    'oauth': "Войти через:",
    'wrong_password': "Неверный логин или пароль",
    'wrong_email': "Некорректный email",
    'password_missing': "Введите пароль",
    'unknown_error': "Неизвестная ошибка",
    'auth_connection_error': "Нет подключения к интернету",
    'password_again': "Пароль еще раз",
    'create_account': "Создать аккаунт",
    'passwords_not_match': "Пароли не совпадают",
    'account_exists': "Аккаунт уже существует",
    'missing_email': "Введите email",
    'too_short_password': "Слишком короткий пароль",
    'back': "Назад",
    'send_again': "Отправить еще раз",
    'email_send': "На ваш адрес {} было отправлено письмо. Перейдите по ссылке в этом письме, "
                  "чтобы подтвердить адрес электронной почты.",
    'sign_out': "Выйти",
    'copy_code': "Скопируйте код и перейдите по ссылке",
    'sign_in_via': "Вход через",

    'blue': "Синий",
    'green': "Зеленый",
    'red': "Красный",
    'pink': "Розовый",
    'orange': "Оранжевый",

    'lang_af': "Африкаанс",
    'lang_sq': "Албанский",
    'lang_am': "Амхарский",
    'lang_ar': "Арабский",
    'lang_hy': "Армянский",
    'lang_az': "Азербайджанский",
    'lang_eu': "Баскский",
    'lang_be': "Белорусский",
    'lang_bn': "Бенгальский",
    'lang_bs': "Боснийский",
    'lang_bg': "Болгарский",
    'lang_ca': "Каталанский",
    'lang_ceb': "Кебуано",
    'lang_ny': "Чичева",
    'lang_zh-cn': "Китайский (упрощенный)",
    'lang_zh-tw': "Китайский (традиционный)",
    'lang_co': "Корсиканский",
    'lang_hr': "Хорватский",
    'lang_cs': "Чешский",
    'lang_da': "Датский",
    'lang_nl': "Голландский",
    'lang_en': "Фнглийский",
    'lang_eo': "Эсперанто",
    'lang_et': "Эстонский",
    'lang_tl': "Филиппинский",
    'lang_fi': "Финский",
    'lang_fr': "Французский",
    'lang_fy': "Фризский",
    'lang_gl': "Галисийский",
    'lang_ka': "Грузинский",
    'lang_de': "Немецкий",
    'lang_el': "Греческий",
    'lang_gu': "Гуджарати",
    'lang_ht': "Гаитянский креольский",
    'lang_ha': "Хауса",
    'lang_haw': "Гавайский",
    'lang_iw': "Иврит",
    'lang_he': "Иврит",
    'lang_hi': "Хинди",
    'lang_hmn': "Хмонг",
    'lang_hu': "Венгерский",
    'lang_is': "Исландский",
    'lang_ig': "Игбо",
    'lang_id': "Индонезийский",
    'lang_ga': "Ирландский",
    'lang_it': "Итальянский",
    'lang_ja': "Японский",
    'lang_jw': "Яванский",
    'lang_kn': "Каннада",
    'lang_kk': "Казахский",
    'lang_km': "Кхмерский",
    'lang_ko': "Корейский",
    'lang_ku': "Курдский (курманджи)",
    'lang_ky': "Кыргызский",
    'lang_lo': "Лаосский",
    'lang_la': "Латынь",
    'lang_lv': "Латышский",
    'lang_lt': "Литовский",
    'lang_lb': "Люксембургский",
    'lang_mk': "Македонский",
    'lang_mg': "Малагасийский",
    'lang_ms': "Малайский",
    'lang_ml': "Малаялам",
    'lang_mt': "Мальтийский",
    'lang_mi': "Маори",
    'lang_mr': "Маратхи",
    'lang_mn': "Монгольский",
    'lang_my': "Бирманский",
    'lang_ne': "Непальский",
    'lang_no': "Норвежский",
    'lang_or': "Одия",
    'lang_ps': "Пушту",
    'lang_fa': "Персидский",
    'lang_pl': "Польский",
    'lang_pt': "Португальский",
    'lang_pa': "Пенджабский",
    'lang_ro': "Румынский",
    'lang_ru': "Русский",
    'lang_sm': "Самоанский",
    'lang_gd': "Шотландский гэльский",
    'lang_sr': "Сербский",
    'lang_st': "Сесото",
    'lang_sn': "Шона",
    'lang_sd': "Синдхи",
    'lang_si': "Сингальский",
    'lang_sk': "Словацкий",
    'lang_sl': "Словенский",
    'lang_so': "Сомалийский",
    'lang_es': "Испанский",
    'lang_su': "Суданский",
    'lang_sw': "Суахили",
    'lang_sv': "Шведский",
    'lang_tg': "Таджикский",
    'lang_ta': "Тамильский",
    'lang_te': "Телугу",
    'lang_th': "Тайский",
    'lang_tr': "Турецкий",
    'lang_uk': "Украинский",
    'lang_ur': "Урду",
    'lang_ug': "Уйгурский",
    'lang_uz': "Узбекский",
    'lang_vi': "Вьетнамский",
    'lang_cy': "Валлийский",
    'lang_xh': "Коса",
    'lang_yi': "Идиш",
    'lang_yo': "Йоруба",
    'lang_zu': "Зулусский",
    'translated_from_af': "Переведено с африкаанс",
    'translated_from_sq': "Переведено с албанского",
    'translated_from_am': "Переведено с амхарского",
    'translated_from_ar': "Переведено с арабского",
    'translated_from_hy': "Переведено с армянского",
    'translated_from_az': "Переведено с азербайджанского",
    'translated_from_eu': "Переведено с баскского",
    'translated_from_be': "Переведено с белорусского",
    'translated_from_bn': "Переведено с бенгальского",
    'translated_from_bs': "Переведено с боснийского",
    'translated_from_bg': "Переведено с болгарского",
    'translated_from_ca': "Переведено с каталанского",
    'translated_from_ceb': "Переведено с кебуано",
    'translated_from_ny': "Переведено с чичева",
    'translated_from_zh-cn': "Переведено с упрощенного китайского",
    'translated_from_zh-tw': "Переведено с традиционного китайского",
    'translated_from_co': "Переведено с корсиканского",
    'translated_from_hr': "Переведено с хорватского",
    'translated_from_cs': "Переведено с чешского",
    'translated_from_da': "Переведено с датского",
    'translated_from_nl': "Переведено с голландского",
    'translated_from_en': "Переведено с английского",
    'translated_from_eo': "Переведено с эсперанто",
    'translated_from_et': "Переведено с эстонского",
    'translated_from_tl': "Переведено с филиппинского",
    'translated_from_fi': "Переведено с финского",
    'translated_from_fr': "Переведено с французского",
    'translated_from_fy': "Переведено с фризского",
    'translated_from_gl': "Переведено с галисийского",
    'translated_from_ka': "Переведено с грузинского",
    'translated_from_de': "Переведено с немецкого",
    'translated_from_el': "Переведено с греческого",
    'translated_from_gu': "Переведено с гуджарати",
    'translated_from_ht': "Переведено с гаитянского креольского",
    'translated_from_ha': "Переведено с хауса",
    'translated_from_haw': "Переведено с гавайского",
    'translated_from_iw': "Переведено с иврита",
    'translated_from_he': "Переведено с иврита",
    'translated_from_hi': "Переведено с хинди",
    'translated_from_hmn': "Переведено с хмонг",
    'translated_from_hu': "Переведено с венгерского",
    'translated_from_is': "Переведено с исландского",
    'translated_from_ig': "Переведено с игбо",
    'translated_from_id': "Переведено с индонезийского",
    'translated_from_ga': "Переведено с ирландского",
    'translated_from_it': "Переведено с итальянского",
    'translated_from_ja': "Переведено с японского",
    'translated_from_jw': "Переведено с яванского",
    'translated_from_kn': "Переведено с каннада",
    'translated_from_kk': "Переведено с казахского",
    'translated_from_km': "Переведено с кхмерского",
    'translated_from_ko': "Переведено с корейского",
    'translated_from_ku': "Переведено с курдского (курманджи)",
    'translated_from_ky': "Переведено с кыргызского",
    'translated_from_lo': "Переведено с лаосского",
    'translated_from_la': "Переведено с латыни",
    'translated_from_lv': "Переведено с латышского",
    'translated_from_lt': "Переведено с литовского",
    'translated_from_lb': "Переведено с люксембургского",
    'translated_from_mk': "Переведено с македонского",
    'translated_from_mg': "Переведено с малагасийского",
    'translated_from_ms': "Переведено с малайского",
    'translated_from_ml': "Переведено с малаялам",
    'translated_from_mt': "Переведено с мальтийского",
    'translated_from_mi': "Переведено с маори",
    'translated_from_mr': "Переведено с маратхи",
    'translated_from_mn': "Переведено с монгольского",
    'translated_from_my': "Переведено с Мьянмы (бирманский)",
    'translated_from_ne': "Переведено с непальского",
    'translated_from_no': "Переведено с норвежского",
    'translated_from_or': "Переведено с Одиа",
    'translated_from_ps': "Переведено с пушту",
    'translated_from_fa': "Переведено с персидского",
    'translated_from_pl': "Переведено с польского",
    'translated_from_pt': "Переведено с португальского",
    'translated_from_pa': "Переведено с панджаби",
    'translated_from_ro': "Переведено с румынского",
    'translated_from_ru': "Переведено с русского",
    'translated_from_sm': "Переведено с самоанского",
    'translated_from_gd': "Переведено с шотландского гэльского",
    'translated_from_sr': "Переведено с сербского",
    'translated_from_st': "Переведено с английского",
    'translated_from_sn': "Переведено с шона",
    'translated_from_sd': "Переведено с синдхи",
    'translated_from_si': "Переведено с сингальского",
    'translated_from_sk': "Переведено со словацкого",
    'translated_from_sl': "Переведено со словенского",
    'translated_from_so': "Переведено с сомалийского",
    'translated_from_es': "Переведено с испанского",
    'translated_from_su': "Переведено с сунданского",
    'translated_from_sw': "Переведено с суахили",
    'translated_from_sv': "Переведено со шведского",
    'translated_from_tg': "Переведено с таджикского",
    'translated_from_ta': "Переведено с тамильского",
    'translated_from_te': "Переведено с телугу",
    'translated_from_th': "Переведено с тайского",
    'translated_from_tr': "Переведено с турецкого",
    'translated_from_uk': "Переведено с украинского",
    'translated_from_ur': "Переведено с урду",
    'translated_from_ug': "Переведено с уйгурского",
    'translated_from_uz': "Переведено с узбекского",
    'translated_from_vi': "Переведено с вьетнамского",
    'translated_from_cy': "Переведено с валлийского",
    'translated_from_xh': "Переведено с коса",
    'translated_from_yi': "Переведено с идиш",
    'translated_from_yo': "Переведено с йоруба",
    'translated_from_zu': "Переведено с зулу",
})
