name: Build
on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Install dependencies
        run: |
          cd "D:\a\GPT-chat\GPT-chat\master"
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build by Pyinstaller
        run: |
          cd "D:\a\GPT-chat\GPT-chat\master"
          pyinstaller --noconfirm GPT-chat.spec
          ls

      - name: Fix Qt6, Update setup.iss
        run: |
          cd "D:\a\GPT-chat\GPT-chat\master"
          python dist/fix_version.py
          ls
          ls build
          ls dist

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: dist/setup.iss
          options: /O+

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: GPT-chat_setup.exe
