name: Build
on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python --version
          python -m venv venv
          venv\Scripts\Activate.ps1
          
          venv\Scripts\python -m pip install -r requirements.txt
          venv\Scripts\python -m pip install --upgrade pyinstaller==6.3.0

      - name: Build by Pyinstaller
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\pyinstaller --noconfirm GPT-chat.spec

      - name: Fix Qt6, Update setup.iss
        run: |
          python fix_version.py

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup.iss
          options: /O+

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GPT-chat_setup.exe
          path: D:\a\GPT-chat\GPT-chat\dist\GPT-chat_setup.exe
