name: Build
on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1
          
          venv\Scripts\python -m pip install -r requirements.txt
          venv\Scripts\python -m pip install --upgrade pyinstaller==6.3.0

      - name: Build by Pyinstaller
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\pyinstaller --noconfirm GPT-chat.spec

      - name: Fix Qt6, Update setup.iss
        run: |
          python fix_version.py

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup.iss
          options: /O+

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GPT-chat_setup.exe
          path: D:\a\GPT-chat\GPT-chat\dist\GPT-chat_setup.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python3.11 -m pip install -r requirements.txt
          python3.11 -m pip install --upgrade pyinstaller==6.3.0

      - name: Build by Pyinstaller
        id: build
        run: |
          pyinstaller --noconfirm GPT-chat.spec
          cd src
          python3 -c "print('version=', __import__('config').APP_VERSION)" > "$GITHUB_OUTPUT"

      - name: Create DEB package
        uses: jiro4989/build-deb-action@v3
        with:
          package: gptchat
          package_root: dist/GPT-chat
          maintainer: SergeiKrivko
          version: ${{ steps.runner.outputs.version }}
          arch: 'amd64'
          desc: 'GPT-chat'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GPT-chat_linux.deb
          path: gptchat_${{ steps.runner.outputs.version }}_amd64.deb

  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python3.11 -m pip install -r requirements.txt
          python3.11 -m pip install --upgrade pyinstaller==6.3.0

      - name: Build by Pyinstaller
        run: |
          pyinstaller --noconfirm GPT-chat.spec
          rm -rf dist/GPT-chat

      - name: Create installer
        uses: QQxiaoming/create-dmg-action@v0.0.2
        with:
          name: 'GPT-chat'
          srcdir: 'dist/GPT-chat.app'

      - run: ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GPT-chat_macos.dmg
          path: GPT-chat.dmg
